### ISSUE TITLE
 No support for automatic agreement.

### ISSUE THREAD

**Issue by DaimyoHub** [CallMePixelMan/ask_lib#1]
Hi !

I see no provided interface that permits to automatically accept a request. It would be interesting to implement such feature. It could be used for commands launched automatically, for instance, in a container, to install some libraries before the deployment step.

The implementation of this feature could bring you to create a "verbose" flag. This flag could allow to not print the request on the screen. It could be great to implement this with the automatic agreement because it is not necessary to print the request if it is automatically accepted.

**Comment by CallMePixelMan** [comment]
Hi,

Because of how the `ask()` function is made, this is an hard feature to add to `ask_lib`. However, I think this could be a really nice fonctionnality to add. I'll try my best to figure out how I could add this, and publish my advancement here if I found something.

Thank you for your suggestion

**Comment by CallMePixelMan** [comment]
Hi back, I think i found a way to solve this by adding a new argument to the `ask()` function, and new constants, there's more comming soon for `ask_lib`. 😉

**Comment by CallMePixelMan** [comment]
`ask_lib 1.1.0` is out ! There's now a `flag` parameter on the `ask()` command and some new constent that you can use to automaticly preselect a response without seeing the question. Thank you again for your suggestion ! 😄
